eslint/json

package.json, src/languages/json-language.js, tests/languages/json-language.test.js
Added `JSONLanguage#visitorKeys`.
- Added `JSONLanguage#visitorKeys`
- Added tests to ensure that `JSONLanguage#visitorKeys` is properly created
Please double check that the following line is included in the merge commit body to ensure we reset the package version number:
Release-As: 0.1.0
=> feat: Add JSONLanguage#visitorKeys

release-please-config.json
Set the initial release version to 0.1.0
Used the `release-as` key in `release-please-config.json` to manually set the initial release version
We'll need to remove this later.
=> fix: Set initial release version in release-please-config.json

.github/workflows/release-please.yml
Switches to https://github.com/googleapis/release-please-action as https://github.com/google-github-actions/release-please-action is deprecated.
Updated `.github/workflows/release-please.yml`.
=> chore: switch to `googleapis/release-please-action`

.github/workflows/release-please.yml, release-please-config.json
Tweak the release-please behavior
- Publish package to JSR
- Simplified `release-please-config.json` because this isn't a monorepo
=> build: Publish to JSR and update release-please config

README.md
Update the README to be clearer
- Added mention that VS Code uses JSON-C
- Added note that `package-lock.json` should normally be excluded from linting
- Added note that `package-lock.json` uses empty keys and so should not be linted with `no-empty-keys`
=> docs: Include info about VS Code and package-lock.json

package.json, src/languages/json-language.js, src/languages/json-source-code.js, tests/languages/json-source-code.test.js
Add `getLoc()` and `getRange()` to `JSONSourceCode`.
- Added `getLoc()` to `JSONSourceCode`
- Added `getRange()` to `JSONSourceCode`
- Added Tests
=> feat: Add getLoc and getRange to JSONSourceCode

README.md, package.json, src/index.js, src/languages/json-language.js, src/rules/no-duplicate-keys.js, src/rules/no-empty-keys.js, tests/rules/no-duplicate-keys.test.js, tests/rules/no-empty-keys.test.js
Add JSON5 support
- Upgraded Momoa to the latest version that supports JSON5
- Updated `no-empty-keys` and `no-duplicate-keys` to support JSON5.
- Added JSON5 tests for both rules.
- Updated README
=> feat: Add JSON5 support

src/index.js, tests/package/exports.js
Exports internal JSONLanguage and JSONSourceCode classes to allow further specialisation, so that plugins for JSON-based domain-specific languages can reuse that code without copying it.
* Added named exports to the project index for `JSONLanguage` and `JSONSourceCode`
This was requested to the JSON plugin maintainer on [Discord](https://discord.com/channels/688543509199716507/1275121520162639913/1275464048095264862). Happy to open an issue for traceability if desired.
=> feat: Export internal constructs for other plugin authors

README.md
Adds a CommonJS usage example. Since the plugin is exported as `default` in CJS, I think it's worth adding this example.
Added the example to README.md.
Discussion on https://github.com/eslint/eslint/pull/18827
=> docs: Add CommonJS example

package.json, src/languages/json-source-code.js, tests/languages/json-source-code.test.js
Refactored to use `@eslint/plugin-kit`
- Use `VisitNodeStep` as the base class for `JSONTraversalStep`
- Use `TextSourceCodeBase` as the base class for `JSONSourceCode`
=> refactor: Use @eslint/plugin-kit

package.json
Make ESLint an optional peer dependency.
Added `peerDependenciesMeta` to `package.json` in order to set `eslint` as an optional peer dependency.
Practically speaking, the plugin doesn't require ESLint to be useful. We are using it in the Code Explorer without ESLint, where it's installation is causing npm errors because Code Explorer uses ESLint v8.x.
It seems like we shouldn't block installation of this package even if ESLint isn't installed or ESLint v8.x is installed, but let me know if anyone has a different opinion. From what I can tell, this change won't have any noticeable effect to most users of this plugin.
=> fix: Don't require ESLint

.npmrc, README.md, package.json, src/languages/json-source-code.js, tests/languages/json-source-code.test.js, tests/plugin/eslint.test.js
Adds support for rule configuration comments and disable directives.
Added `getInlineConfigNodes()`, `getDisableDirectives()` and `applyInlineConfig()` methods to the `JSONSourceCode` class.
Fixes #21
Unlike the JS language implementation (SourceCode in eslint/eslint), in this implementation rule configs, `eslint-disable` and `eslint-enable` can be Line comments. We wanted to implemented this in the JS language as well (https://github.com/eslint/rfcs/pull/34), and eventually did but reverted the change due to backwards compatibility reasons (https://github.com/eslint/eslint/issues/14960). Since there were no backwards compatibility concerns here, it seemed fine to allow this, but …
=> feat: Add support for config comments

tests/rules/no-duplicate-keys.test.js
Improves testing of the `no-duplicate-keys` rule.
Added `data` property to invalid test cases.
=> test: Add `data` in tests for no-duplicate-keys rule

README.md, package.json, src/languages/json-language.js, tests/languages/json-language.test.js
Add support for trailing commas to the JSONC language.
This pull request introduces support for allowing trailing commas in JSONC files and includes several updates to the codebase and documentation to reflect this new feature. The most important changes include adding a new option to enable trailing commas, updating the `JSONLanguage` class to validate and handle this option, and adding tests to ensure the feature works as expected.
* **README.md**: Added a section explaining how to enable trailing commas in JSONC files using the `allowTrailingCommas` language option. 
* **`src/languages/json-language.js`**:
* Added a new typedef for `JSONLanguageOptions` to include the …
=> feat: Add allowTrailingCommas option for JSONC

src/rules/no-unsafe-values.js, tests/rules/no-unsafe-values.test.js
Introduce a new rule for checking common interchange problems
Added a rule for:
- non-finite (Infinity, null, NaN) values.
- lone surrogates due to UTF16
fixes #29
tests are somewhat limited by using already parsed values so I avoided trying to reparse for getting exact locations within strings and/or couldn't check array/string bounds since things error before getting to the rules processing phase.
=> feat: rule no-unsafe-values

tests/rules/no-unsafe-values.test.js
Update `no-unsafe-values` tests.
Added `data` fields to all tests using `messageId` for lone surrogate errors.
=> test: Add data into no-unsafe-values tests

README.md, src/index.js
Enables `no-unsafe-values` rule to be used.
Added the rule to `plugin.rules`, `recommended` configuration and README.
Follow up to https://github.com/eslint/json/pull/30.
=> feat: enable `no-unsafe-values` and add it to recommended configuration

tests/package/exports.js, tests/plugin/eslint.test.js
Ensures that all rules available in `src/rules` are exported in `plugin.rules`. Also adds a test for plugin configs that would fail if, for example, the config enables a non-existent rule.
Added tests.
https://github.com/eslint/json/pull/51
If this looks good, I'll add similar tests to `@eslint/markdown` and `@eslint/css`.
=> test: Ensure all rules are exported

.github/workflows/ci.yml, package.json, src/index.js, src/rules/no-duplicate-keys.js, src/rules/no-empty-keys.js, src/rules/no-unsafe-values.js, tests/types/tsconfig.json, tests/types/types.test.ts
-   [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).
Add type tests and fix some problems in the types.
Added type tests to the CI workflow. I had to fix some minor issues in the typings of rules metadata and in the recommended config to match the signature of `ESLint.Plugin`. This is why this pull request is tagged `fix:`.
fixes #61
=> fix: add type tests

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/release-please.yml, README.md, package.json
Update how we post release announcements. This will now post to Twitter, Mastodon, and Bluesky.
- Switched to use `@humanwhocodes/crosspost` to post across multiple services in one step
- Added organization secrets and variables for the BlueSky info
I've tested this on my own project and it worked, but want to just try this out on one of our repos to verify that everything is configured correctly before rolling out across the org.
=> chore: Post release announcements across services

package.json, tests/rules/no-duplicate-keys.test.js
Ensure that escaped and unescaped keys of objects that evaluate to the same string still trigger rules that prevent duplicate keys.
Added tests with `o` replaced with `\\u006f` in strategic places.  Note that the double-backslash is necessary so that the JSON parser is processing the backslash, not the JS parser running the tests.
Refs #68
Note that this is affected by
https://github.com/humanwhocodes/momoa/issues/164
in the sense that in JSON5 mode, unquoted escaped
keys are not yet unescaped in the same was as
all other keys, and will not trigger this lint
yet.  When the momoa issue is fixed, released, and we have updated to that version, uncomment the
last test in no-duplicate-keys.test.js.
Suggest that we create a separate issue in this
repo to track that change.
=> test: Matching escaped and unescaped keys

README.md, src/index.js, src/rules/top-level-interop.js, tests/rules/top-level-interop.test.js
A new rule that checks that the top-level item in a JSON file is either an array or an object, as suggested by RFC8259.  Not turned on in the recommended config because the software that had this issue is almost entirely obsolete.
Refs #68.
As discussed in #68, add a new rule to enforce the top-level item in a JSON doc be an array or object.
Added src/rules/top-level-interop.js and tests/rules/top-level-interop.test.js
Refs #68
Should this be in the recommended set?  I could be persuaded either way.
=> feat: Add top-level-interop rule

README.md, src/rules/no-unsafe-values.js, tests/rules/no-unsafe-values.test.js
Catch subnormals, numbers that are flushed to zero,
and overly-large integers in no-unsafe-values.
Added three numeric cases to no-unsafe-values.js:
- Flushed to zero: the parsed value is zero, but the original text implies that zero was not intended.  Example: `1e-400`
- Overly-large integers: the original text looks like an integer (no decimal point or exponent), but the value is outside the range `[Number.MIN_SAFE_INTEGER, Number.MAX_SAFE_INTEGER]`.  `Example: 9007199254740992`
- Subnormals: these are numbers that have reduced precision in an IEEE-754 f64.  Example: `2.2250738585072009e-308`
Refs #68
Please double-check my error messages for your preferences.
=> feat: Catch more unsafe numbers

package.json, tests/types/cjs-import.test.cts, tests/types/tsconfig.json
Similar to eslint/rewrite#143, this PR ensures that the `@eslint/json` types can be imported from a CommonJS module when [`moduleResolution`](https://www.typescriptlang.org/tsconfig/#moduleResolution) is one of `'node16'` or `'nodenext'`. This is currently not possible because of an issue with the types in `@eslint/plugin-kit` that has been fixed in the latest version `v0.2.5`.
* Updated dependency `@eslint/plugin-kit` to version spec `"^0.2.5"`.
* Made `@eslint/core` a runtime dependency of this package.
* Added tests to ensure that `@eslint/json` can be imported from a `.cts` file.
refs eslint/rewrite#143.
=> fix: make types usable in CommonJS

README.md, package.json, src/index.js, src/rules/sort-keys.js, tests/rules/sort-keys.test.js
Adds a `sort-keys` rule for JSON that mimics the functionality of the existing `sort-keys` for JS.
Added a `sort-keys` rule and tests.
Fixes #75 
I started by copying over the existing code for JS `sort-keys`, but it required some big modifications in order to work on JSON. It would be nice if there was an automated way to make sure this `sort-keys` maintains parity with that `sort-keys` to keep things consistent across ESLint packages, but JS and JSON are different enough that I'm not sure how it could be done. https://github.com/eslint/json/blob/7fe278238579128a6fdb13f9ce67674f0b9e22f1/tests/rules/sort-keys.test.js#L2
~~Note that I added a TODO for how comments affect line-separated groups~~
=> feat: Add sort-keys rule

package.json, src/rules/no-duplicate-keys.js, src/rules/no-empty-keys.js, src/rules/no-unnormalized-keys.js, src/rules/no-unsafe-values.js, src/rules/sort-keys.js, src/rules/top-level-interop.js, src/types.ts
Updates types throughout.
* [`src/rules/no-duplicate-keys.js`](diffhunk://#diff-969f0d66f1cfc2d4e41aadd9f8c363d0ec36ce01d966b9abc5ef1d5eef2ab22eL19-R19): Changed the rule definition to use a `const rule` and exported it separately. [[1]](diffhunk://#diff-969f0d66f1cfc2d4e41aadd9f8c363d0ec36ce01d966b9abc5ef1d5eef2ab22eL19-R19) [[2]](diffhunk://#diff-969f0d66f1cfc2d4e41aadd9f8c363d0ec36ce01d966b9abc5ef1d5eef2ab22eR69-R70)
* [`src/rules/no-empty-keys.js`](diffhunk://#diff-78a5bba7f29b557cf63ae6bf91225c924b3b26057b9b7850e5126e2287f604eaL18-R18): Changed the rule definition to use a `const rule` and exported it separately. [[1]](diffhunk://#diff-78a5bba7f29b557cf63ae6bf91225c924b3b26057b9b7850e5126e2287f604eaL18-R18) [[2]](diffhunk://#diff-78a5bba7f29b557cf63ae6bf91225c924b3b26057b9b7850e5126e2 …
=> fix: Update types and apply to all rules

package.json, tests/types/types.test.ts
Add a type test
Updated package.json to use the latest `eslint` version and re-enabled a type test to check if the plugin is assignable to `ESLint.Plugin`.
refs eslint/eslint#19531
=> test: re-enable `ESLint.Plugin` type test

src/types.ts, tests/types/tsconfig.json, tests/types/types.test.ts
After using this package in with the new [`verbatimModuleSyntax`](https://www.typescriptlang.org/tsconfig/#verbatimModuleSyntax) TypeScript compiler option, I hit the below error.
```sh
error TS1484: 'ElementNode' is a type and must be imported using a type-only import when 'verbatimModuleSyntax' is enabled.
error TS1484: 'ObjectNode' is a type and must be imported using a type-only import when 'verbatimModuleSyntax' is enabled.
...
```
Changed to a type-only import for imports from `@humanwhocodes/momoa`.
Related to #84.
Only one line changed.
=> fix: Update `types.ts` for compatibility with `verbatimModuleSyntax`

package.json, rollup.config.js, src/index.js, src/languages/json-language.js, src/languages/json-source-code.js, src/rules/no-duplicate-keys.js, src/rules/no-empty-keys.js, src/rules/no-unnormalized-keys.js, src/rules/no-unsafe-values.js, src/rules/sort-keys.js, src/rules/top-level-interop.js, src/types.ts, tools/build-cts.js, tools/dedupe-types.js
To simplify and extend the existing types in the package.
Primarily:
1. Switched to using `@import` in JSDoc comments, which allows importing generic types. That allowed a bunch of optimizations.
1. Removed `IJSONLanguage` and `IJSONSourceCode`, swapping them out for the actual classes, both of which now have an `@implements` directly on their declarations.
1. Updated `JSONRuleDefinition` based on discussion with @fasttime.
1. Updated all of the rules accordingly. 
1. Updated `dedupe-types.js` to take into account `@import` statements.
Specifics:
* [`src/languages/json-language.js`](diffhunk://#diff-946ef0a1cd314d57cad8d20980143652c62ee216c556246c67e13875ded7180aL18-R35): Consolidated type definitions and import statements for `@humanwhocodes/momoa` and `@eslint/core`, and updated the …
=> feat!: Update package types for better reuse

tests/types/types.test.ts
Hello,
I've implemented tests for `JSONRuleDefinition` by referencing the existing test in [`@eslint/markdown`](https://github.com/eslint/markdown/blob/main/tests/types/types.test.ts#L87-L162).
I've added some tests.
=> test: create tests for `JSONRuleDefinition`

package.json, src/languages/json-source-code.js, tests/types/types.test.ts
This pull request updates `JSONSourceCode` to extend `TextSourceCodeBase`
- Upgraded @eslint/core and @eslint/plugin-kit to latest versions
- Switched `JSONSourceCode` to extend `TextSourceCodeBase`
=> refactor: switch JSONSourceCode to extend TextSourceCodeBase

README.md
Hello,
I've fixed a typo and added links.
I believe the typo was missing from [eslint/json#94](https://github.com/eslint/json/pull/94).
=> docs: fix a typo and add links

README.md
In this PR, I've fixed wrong `bun` command.
This is follow-up to https://github.com/eslint/rewrite/pull/222.
Currently, the command `bun install package` doesn’t work as expected — the correct command is `bun add`.
References:
- https://bun.sh/docs/cli/install
- https://bun.sh/docs/cli/add
=> docs: fix wrong `bun` command

package.json, src/types.ts
Simplify type definitions.
* Refactored the type definition of `JSONRuleDefinition` using the core [`CustomRuleDefinitionType`](https://github.com/eslint/rewrite/blob/core-v0.15.0/packages/core/src/types.ts#L598-L631) type.
* Redefined `JSONRuleDefinitionTypeOptions` as an alias for the core [`CustomRuleTypeDefinitions`](https://github.com/eslint/rewrite/blob/core-v0.15.0/packages/core/src/types.ts#L589-L596) type.
* Also upgraded `@eslint/core` to v0.15.
refs eslint/rewrite#177
Related PRs: eslint/eslint#19949, eslint/css#203, eslint/markdown#471
=> refactor: use `CustomRuleDefinitionType` in `JSONRuleDefinition`

src/languages/json-source-code.js
Hi,
In this PR, I've added missing type annotations to variables.
Adding type annotations helps improve type safety, and I noticed that some variables were missing them, so I went ahead and added the necessary annotations.
=> refactor: add missing type annotations to variables

package.json, tests/types/types.test.ts
Hi,
This PR is follow-up to https://github.com/eslint/eslint/pull/19995.
You can find more details about this change in https://github.com/eslint/rewrite/issues/234.
- Updated `@eslint/core` to allow arbitrary types for `meta.docs.recommended` in custom rules.
- Upgraded other dependencies to the latest versions.
- Updated type tests.
=> fix: allow any type for `meta.docs.recommended` in custom rules

src/rules/no-unnormalized-keys.js
In this PR, I've updated the `no-unnormlized-keys` rule to use `defaultOptions`.
Previously, the rule used custom logic to extract its default value.
According to MDN and `@types/node`, the default value for `String.prototype.normalize` is `"NFC"`, so I've set it as the default.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize#parameters
I've updated the `no-unnormlized-keys` rule to use `defaultOptions`.
N/A
N/A
=> refactor: use `defaultOptions` in `no-unnormalized-keys`

tests/rules/no-duplicate-keys.test.js, tests/rules/no-empty-keys.test.js, tests/rules/no-unnormalized-keys.test.js, tests/rules/top-level-interop.test.js
In this PR, I've added missing `json/jsonc` tests for rules.
Some rules already have dedicated tests for `json` and `json5`, but were missing `jsonc` tests. So, I've added those as well.
I've also included additional test cases in `top-level-interop`, which I believe will help improve consistency across the tests.
I've added missing `json/jsonc` tests for rules.
N/A
N/A
=> test: add missing `json/jsonc` tests for rules
